"""Константы приложения users."""

USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

USERS_PER_PAGE = 12

AVATAR_SIZE_PX = 200
AVATAR_FONT_SIZE_PX = 100
AVATAR_PRIMARY_FONT = "arial.ttf"
AVATAR_FALLBACK_FONT = "DejaVuSans.ttf"
AVATAR_TEXT_COLOR = (255, 255, 255)
AVATAR_TEXT_VERTICAL_OFFSET_PX = 6
AVATAR_BG_CHANNEL_BASE = 80
AVATAR_BG_CHANNEL_RANGE = 100
